#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'arrayManipulation' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY queries
#

def arrayManipulation(n, queries):
    prefix_sum = [0.00] * (n + 2)
    
    for i in range(len(queries)):
        l,r,k = queries[i]
        
        prefix_sum[l] += k
        prefix_sum[r + 1] -= k
    
    for i in range(1,len(prefix_sum)):
        prefix_sum[i] += prefix_sum[i - 1]
    
    max_val = 0
    
    for i in range(len(prefix_sum)):
        max_val = max(max_val,prefix_sum[i])
    
    return int(max_val)
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
