#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countSwaps' function below.
#
# The function accepts INTEGER_ARRAY a as parameter.
#

def countSwaps(a):
    
    count = 0
    flag = 0
    for index in range(len(a)):
        
        for  j in range(len(a) - (index + 1)):
            if a[j] > a[j + 1]:
                count += 1
                a[j], a[j + 1] = a[j + 1], a[j]
                flag = 1
        
        if flag == 0:
            break
    print("Array is sorted in " + str(count) + " swaps.") 
    print("First Element: " + str(a[0]))
    print("Last Element: " + str(a[-1])) 
   
    # Write your code here

if __name__ == '__main__':
    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    countSwaps(a)
