#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    
    for index in range(1,n):
        val = arr[index]
        right = index
        if val < arr[right - 1]:
            while right > 0 and arr[right - 1] > val:
                arr[right] = arr[right - 1]
                right -= 1
                print(*arr)   
            arr[right] = val 
            print(*arr)

        
        
    # Write your code here

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
